On Error Resume Next

 Dim objADSysInfo : Set objADSysInfo = CreateObject("ADSystemInfo") 
 Dim objUser : Set objUser = GetObject("LDAP://" & objADSysInfo.UserName) 
 Dim IfExist : Set IfExist = "" 
 IfExist = objUser.uidNumber
	if IfExist = "" Then
		msgbox "In order to enable your SAP user for Linux login please open a request "&vbcrlf&"using the following page, after clicking OK: "
		CreateObject("WScript.Shell").Run("https://ifp.wdf.sap.corp/itform/zitform.htm?formname=_LBS_LINUX1")
	Else 
		msgbox "Your SAP user already enabled for Linux login." 
		
	End If

'' SIG '' Begin signature block
'' SIG '' MIIPtgYJKoZIhvcNAQcCoIIPpzCCD6MCAQExDjAMBggq
'' SIG '' hkiG9w0CBQUAMGYGCisGAQQBgjcCAQSgWDBWMDIGCisG
'' SIG '' AQQBgjcCAR4wJAIBAQQQTvApFpkntU2P5azhDxfrqwIB
'' SIG '' AAIBAAIBAAIBAAIBADAgMAwGCCqGSIb3DQIFBQAEEKkK
'' SIG '' yYrdsvnBAdZPIWsQ0mqgggxTMIICbDCCAdWgAwIBAgID
'' SIG '' AQAAMA0GCSqGSIb3DQEBBQUAMEoxCzAJBgNVBAYTAkRF
'' SIG '' MRswGQYDVQQKExJteVNBUC5jb20gU29mdHdhcmUxHjAc
'' SIG '' BgNVBAMTFW15U0FQLmNvbSBTb2Z0d2FyZSBDQTAeFw05
'' SIG '' OTA3MTgxMjAwMDBaFw0zODAxMDExMjAwMDBaMEoxCzAJ
'' SIG '' BgNVBAYTAkRFMRswGQYDVQQKExJteVNBUC5jb20gU29m
'' SIG '' dHdhcmUxHjAcBgNVBAMTFW15U0FQLmNvbSBTb2Z0d2Fy
'' SIG '' ZSBDQTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA
'' SIG '' /vzL17Z8sSTwrSCneymRjim/A0TrZntRr7DD8VcZujv+
'' SIG '' LD5ldN7qcNsl7w9o1QX7p8g3+FWOoohJXX+vSKhTy8NJ
'' SIG '' veQhaHJ36qd5GqK+J0Hju2ro0rhephVNjJ6wDtRevJV1
'' SIG '' 9+7wiEQzGXHcGtggQhwHi6hoLIux+L4AMWu+wXcCAwEA
'' SIG '' AaNgMF4wDAYDVR0TBAUwAwEB/zAOBgNVHQ8BAf8EBAMC
'' SIG '' AYYwHQYDVR0OBBYEFJlSwiGC0Bfi1A/aA0qlrMA30n3c
'' SIG '' MB8GA1UdIwQYMBaAFJlSwiGC0Bfi1A/aA0qlrMA30n3c
'' SIG '' MA0GCSqGSIb3DQEBBQUAA4GBAJdYJPkToTNaBvqgga75
'' SIG '' cFjvQe4EFcMBjB7BZFvUyjBrrqH3OtmKiz6siNVKC9UU
'' SIG '' vR/jR14+t1Pa1NWa0t9cFciiOE6a6Kbdd2CDbqm9nYL8
'' SIG '' 0jJ0TkTZ/DEseih1pMcGz/hr6AzMyQdUt2mOViALWOFN
'' SIG '' DMdEpz1zVz0npZdDqAc7MIICdDCCAd2gAwIBAgIDAQAK
'' SIG '' MA0GCSqGSIb3DQEBBQUAMEoxCzAJBgNVBAYTAkRFMRsw
'' SIG '' GQYDVQQKExJteVNBUC5jb20gU29mdHdhcmUxHjAcBgNV
'' SIG '' BAMTFW15U0FQLmNvbSBTb2Z0d2FyZSBDQTAeFw0xMDAx
'' SIG '' MDEwMDAwMDBaFw0xNTAxMDEwMDAwMDBaMEUxCzAJBgNV
'' SIG '' BAYTAkRFMRswGQYDVQQKExJteVNBUC5jb20gU29mdHdh
'' SIG '' cmUxGTAXBgNVBAMTEFNBUCBJVCBXb3Jrc3BhY2UwgZ8w
'' SIG '' DQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAP/ylxM1uDSA
'' SIG '' Uy2lfblAKHt/g1l3gbOBIaVCYx9vwblRL0IO84cIZyKp
'' SIG '' //zyem/08WmG6WC1iTsvGLAXKiIGiNsCUi0bCDBIs8p9
'' SIG '' +LW2nmHegv2S4XfAGJoSx9LjLztG2qnFVB/ok5JgB2Ux
'' SIG '' 73ro1LU/rWucCUEiU7Vhs3hDpn+ZAgMBAAGjbTBrMBEG
'' SIG '' CWCGSAGG+EIBAQQEAwIAEDAJBgNVHRMEAjAAMAsGA1Ud
'' SIG '' DwQEAwID+DAdBgNVHQ4EFgQU3+0tiYS9koQS0eE8fRTh
'' SIG '' aEdNEv4wHwYDVR0jBBgwFoAUmVLCIYLQF+LUD9oDSqWs
'' SIG '' wDfSfdwwDQYJKoZIhvcNAQEFBQADgYEAANhjhCEUwJM2
'' SIG '' 3dBnfM1C4Bu090TLSPhdeA4q43VNH9lJDciDJsMFfHTS
'' SIG '' b53KMMYMpnswb/n0PHMmEZOL4P8EQRr4KME4mfYp3gHI
'' SIG '' Br7Hmb5pOXdp1oxELP0R5mbbtJOI8gP97F/3NbjrDsM7
'' SIG '' qtAX2RrgH1XXCZKL65CzI7yRbBIwggOfMIICh6ADAgEC
'' SIG '' AhB5oqWF+dEVQhPZuD72to3tMA0GCSqGSIb3DQEBBQUA
'' SIG '' MFMxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5WZXJpU2ln
'' SIG '' biwgSW5jLjErMCkGA1UEAxMiVmVyaVNpZ24gVGltZSBT
'' SIG '' dGFtcGluZyBTZXJ2aWNlcyBDQTAeFw0xMjA1MDEwMDAw
'' SIG '' MDBaFw0xMjEyMzEyMzU5NTlaMGIxCzAJBgNVBAYTAlVT
'' SIG '' MR0wGwYDVQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlvbjE0
'' SIG '' MDIGA1UEAxMrU3ltYW50ZWMgVGltZSBTdGFtcGluZyBT
'' SIG '' ZXJ2aWNlcyBTaWduZXIgLSBHMzCBnzANBgkqhkiG9w0B
'' SIG '' AQEFAAOBjQAwgYkCgYEAqVlmdNo9in162Pz1gER7/kdq
'' SIG '' FFVOUEcL7NPtzvY4909pubHwtniCCox2FmfiAq23DaWK
'' SIG '' 9gP8ZtP8CC3MtXNZe4ncM25mWl5SN7Ri0ZJZNRSLRaxZ
'' SIG '' sk0kopiUaEJynzpo4muLniIt9JhOmsavs+SgqzwovyPh
'' SIG '' 13Kk8hBTZ653r1ECAwEAAaOB4zCB4DAMBgNVHRMBAf8E
'' SIG '' AjAAMDMGA1UdHwQsMCowKKAmoCSGImh0dHA6Ly9jcmwu
'' SIG '' dmVyaXNpZ24uY29tL3Rzcy1jYS5jcmwwFgYDVR0lAQH/
'' SIG '' BAwwCgYIKwYBBQUHAwgwNAYIKwYBBQUHAQEEKDAmMCQG
'' SIG '' CCsGAQUFBzABhhhodHRwOi8vb2NzcC52ZXJpc2lnbi5j
'' SIG '' b20wDgYDVR0PAQH/BAQDAgeAMB4GA1UdEQQXMBWkEzAR
'' SIG '' MQ8wDQYDVQQDEwZUU0ExLTMwHQYDVR0OBBYEFLS38YlJ
'' SIG '' JmDnZepzrtzTOM2/V5JvMA0GCSqGSIb3DQEBBQUAA4IB
'' SIG '' AQAemKont3i1CLXJcm2338AOmKY1xIjJ0vZt8Usa+9X5
'' SIG '' LZkAntHnm4vhP705gAxmzQe8XJhUppS6ENFOi6v1b2XM
'' SIG '' ZwmigHxS6A4D1mt6xgUY7MisQnwHLKc9CGbcAO39lB1z
'' SIG '' 8nKYk7ER1o/vjuqs9JZRDNCN3zFST16vfadKdeZOziuf
'' SIG '' KSvnz12fA35uJ3sjrWIpZq+S6CzOvZx/3M0XPEPCCT91
'' SIG '' Rcee5Ndgf5fG5KrHafX8zXSsLLBIwVBOcFYetTXTjr6x
'' SIG '' 7ay9/gzshX3Vu4VmRBldn5PrgrpjntN8Yf/IG9kjWH8w
'' SIG '' o2ahOSZeksM8yzcy+vWjjdzVsKPpJTZV14H6MIIDxDCC
'' SIG '' Ay2gAwIBAgIQR78Zld+NUkZD99ttSA0xpDANBgkqhkiG
'' SIG '' 9w0BAQUFADCBizELMAkGA1UEBhMCWkExFTATBgNVBAgT
'' SIG '' DFdlc3Rlcm4gQ2FwZTEUMBIGA1UEBxMLRHVyYmFudmls
'' SIG '' bGUxDzANBgNVBAoTBlRoYXd0ZTEdMBsGA1UECxMUVGhh
'' SIG '' d3RlIENlcnRpZmljYXRpb24xHzAdBgNVBAMTFlRoYXd0
'' SIG '' ZSBUaW1lc3RhbXBpbmcgQ0EwHhcNMDMxMjA0MDAwMDAw
'' SIG '' WhcNMTMxMjAzMjM1OTU5WjBTMQswCQYDVQQGEwJVUzEX
'' SIG '' MBUGA1UEChMOVmVyaVNpZ24sIEluYy4xKzApBgNVBAMT
'' SIG '' IlZlcmlTaWduIFRpbWUgU3RhbXBpbmcgU2VydmljZXMg
'' SIG '' Q0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
'' SIG '' AQCpyrKkzM0grwp9iayHdfC0TvHfwQ+/Z2G9o2Qc2rv5
'' SIG '' yjOrhDCJWH6M22vdNp4Pv9HsePJ3pn5vPL+Trw26aPRs
'' SIG '' lMq9Ui2rSD31ttVdXxsCn/ovax6k96OaphrIAuF/TFLj
'' SIG '' DmDsQBx+uQ3eP8e034e9X3pqMS4DmYETqEcgzjFzDVct
'' SIG '' zXg0M5USmRK53mgvqubjwoqMKsOLIYdmvYNYV291vzyq
'' SIG '' JoddyhAVPJ+E6lTBCm7E/sVK3bkHEZcifNs+J9EeeOyf
'' SIG '' Mcnx5iIZ28SzR0OaGl+gHpDkXvXufPF9q2IBj/VNC97Q
'' SIG '' Ilaolc2uiHau7roN8+RN2aD7aKCuFDuzh8G7AgMBAAGj
'' SIG '' gdswgdgwNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzAB
'' SIG '' hhhodHRwOi8vb2NzcC52ZXJpc2lnbi5jb20wEgYDVR0T
'' SIG '' AQH/BAgwBgEB/wIBADBBBgNVHR8EOjA4MDagNKAyhjBo
'' SIG '' dHRwOi8vY3JsLnZlcmlzaWduLmNvbS9UaGF3dGVUaW1l
'' SIG '' c3RhbXBpbmdDQS5jcmwwEwYDVR0lBAwwCgYIKwYBBQUH
'' SIG '' AwgwDgYDVR0PAQH/BAQDAgEGMCQGA1UdEQQdMBukGTAX
'' SIG '' MRUwEwYDVQQDEwxUU0EyMDQ4LTEtNTMwDQYJKoZIhvcN
'' SIG '' AQEFBQADgYEASmv56ljCRBwxiXmZK5a/gqwB1hxMzbCK
'' SIG '' WG7fCCmjXsjKkxPnBFIN70cnLwA4sOTJk06a1CJiFfc/
'' SIG '' NyFPcDGA8Ys4h7Po6JcA/s9Vlk4k0qknTnqut2FB8yrO
'' SIG '' 58nZXt27K4U+tZ212eFX/760xX71zwye8Jf+K9M7Uhsb
'' SIG '' OCf3P0oxggLNMIICyQIBATBRMEoxCzAJBgNVBAYTAkRF
'' SIG '' MRswGQYDVQQKExJteVNBUC5jb20gU29mdHdhcmUxHjAc
'' SIG '' BgNVBAMTFW15U0FQLmNvbSBTb2Z0d2FyZSBDQQIDAQAK
'' SIG '' MAwGCCqGSIb3DQIFBQCgTjAQBgorBgEEAYI3AgEMMQIw
'' SIG '' ADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAfBgkq
'' SIG '' hkiG9w0BCQQxEgQQShRPKQifX8ml3XpyyHH6MTANBgkq
'' SIG '' hkiG9w0BAQEFAASBgIklc2zoUNtQM7NpW4hGzUrBJXOY
'' SIG '' W/0tZrEUJJQcXIFneSyihUz52xwOgRT8Ph+q0yCLYmKe
'' SIG '' wbiPhdymoQWdu/AyqJvGxkBL/eJLj50AqiwQz/QCETBc
'' SIG '' iaCqRw8ADHSV+wvn7n2xEctrFuooSYxjGsyyYUOqwIaF
'' SIG '' zfmojKcc4AI2oYIBfzCCAXsGCSqGSIb3DQEJBjGCAWww
'' SIG '' ggFoAgEBMGcwUzELMAkGA1UEBhMCVVMxFzAVBgNVBAoT
'' SIG '' DlZlcmlTaWduLCBJbmMuMSswKQYDVQQDEyJWZXJpU2ln
'' SIG '' biBUaW1lIFN0YW1waW5nIFNlcnZpY2VzIENBAhB5oqWF
'' SIG '' +dEVQhPZuD72to3tMAkGBSsOAwIaBQCgXTAYBgkqhkiG
'' SIG '' 9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEP
'' SIG '' Fw0xMjA3MDIxMjQwMTdaMCMGCSqGSIb3DQEJBDEWBBSH
'' SIG '' Aoyza7mvjkO/L2KPoxAirryvkTANBgkqhkiG9w0BAQEF
'' SIG '' AASBgB3wR6h/YGrlMUjtmV7/4Ij9izitTxP9bbxRJHb7
'' SIG '' A4dtIsB6tlXo03QxPoYwYjWgIWDu0V15U8WaSOPSig5d
'' SIG '' PB2KMvEuuyv0dELXRraBWc3DTVWLNO703KD90VCcsE6d
'' SIG '' 2IAjFra0SXGocGplWzb86FxhbJJvno4ll+msv705EdNo
'' SIG '' End signature block
